name: Setup environment

on:
  workflow_call:
  
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Hello World
        run: echo Hello World!
  
