name: Ruby API tests

on:
  workflow_call:
  
jobs:
  environment_setup:
    runs-on: ubuntu-latest
    steps:      
    - name: SETUP RUBY
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: CONFIG FREETDS FOR DB
      run: sudo apt-get install freetds-dev -y
      
  environment_repository:
    needs: environment_setup
    steps:   
    - name: CHECKOUT REPOSITORY
      uses: actions/checkout@v3

    - name: SETUP GEMS
      run: bundle install

    - name: RUN TESTS
      run: rake "parallel_tests[stg, 5, @full_smoke]"