name: Ruby API tests

on:
  workflow_call:
    inputs:
      env:
        type: choice
        description: Choose the environment you want to run the tests 
        options:
        - dev
        - stg
        - prd
        required: true
      threads:  
        type: choice
        description: Choose how many parallels you want to run
        options:
        - '1'
        - '2'
        - '3'
        required: true
      tag:    
        type: string
        description: Enter the tag of the scenario or suite you want to run
        required: true

jobs:
  environment_setup:
    runs-on: ubuntu-latest
    steps:      
    - name: SETUP RUBY
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: CONFIG FREETDS FOR DB
      run: sudo apt-get install freetds-dev -y
      
  environment_repository:
    needs: environment_setup
    runs-on: ubuntu-latest
    steps:   
    - name: CHECKOUT REPOSITORY
      uses: actions/checkout@v3

    - name: SETUP GEMS
      run: bundle install

    - name: RUN TESTS
      run: rake "parallel_tests[${{ inputs.env }}, ${{ inputs.threads }}, ${{ inputs.tag }}]"