name: Setup environment

on:
  workflow_call:
  
jobs:
  environment_setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: INSTALL RUBY
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: CONFIG FREETDS FOR DB
        run: sudo apt-get install freetds-dev -y
