name: Ruby API tests

on:
  workflow_call:
    inputs:
      env:
        description: Choose the environment you want to run the tests 
        required: true
        type: choice
        options:
        - dev
        - stg
        - prd
      threads:
        description: Choose how many parallels you want to run
        required: true
        type: choice
        options:
        - 1
        - 2
        - 3
      tag:
        description: Enter the tag of the scenario or suite you want to run
        required: true
        type: string

jobs:
  environment_setup:
    runs-on: ubuntu-latest
    steps:      
    - name: SETUP RUBY
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: CONFIG FREETDS FOR DB
      run: sudo apt-get install freetds-dev -y
      
  environment_repository:
    needs: environment_setup
    runs-on: ubuntu-latest
    steps:   
    - name: CHECKOUT REPOSITORY
      uses: actions/checkout@v3

    - name: SETUP GEMS
      run: bundle install

    - name: RUN TESTS
      run: rake "parallel_tests[${{ github.event.inputs.env }}, ${{ github.event.inputs.threads }}, ${{ github.event.inputs.tag }}]"