name: Ruby API tests

on:
  workflow_call:
  
jobs:
  environment_setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: SETUP RUBY
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'

    - name: CONFIG FREETDS FOR DB
      run: sudo apt-get install freetds-dev -y

    - name: CLONE PROJECT
      uses: actions/checkout@v3
      with:
        ref: master
        repository: jhonata-santos/ruby-automation-api-template
      
    - name: SETUP GEMS
      run: bundle install